# Generated by Django 5.2.1 on 2025-06-01 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('css_url', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator()])),
                ('js_url', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator()])),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Admin Theme',
                'verbose_name_plural': 'Admin Themes',
            },
        ),
    ]
