# Generated by Django 5.2.1 on 2025-06-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_theme_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admintheme',
            options={},
        ),
        migrations.AddField(
            model_name='admintheme',
            name='accessibility_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admintheme',
            name='ui_suggestions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
