# Generated by Django 5.2.1 on 2025-06-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_theme_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintheme',
            name='css_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admintheme',
            name='js_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
